
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['builds', 'submit', '--tag', 'gcr.io/$testeelevador/TesteElevador', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$testeelevador/TesteElevador']
timeout: '1600s'
images:
- 'gcr.io/$testeelevador/TesteElevador'
